- name: HF-Endpoint-Prompts
  # uses: fjogeleit/http-request-action@eab8015483ccea148feff7b1c65f320805ddc2bf
  uses: fjogeleit/http-request-action@v1.14.1
  with:
    # Request URL
    url: https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-beta
    # Request Method
    method: POST
    # Content Type
    contentType: application/json
    # Request Body as JSON String
    data: # optional, default is {}
    # Map of absolute file paths as JSON String
    files: # optional, default is {}
    # A single absolute file path
    file: # optional
    # Request Timeout in Sec
    timeout: 5000
    # Bearer Authentication Token
    bearerToken: # optional
    # Prevent this Action to fail if the request respond without an response
    preventFailureOnNoResponse: # optional
    # Persist the response data to the specified file path
    responseFile: # optional
    # optional amount of retries if the request fails
    retry: # optional
    # wait time between retries in milliseconds
    retryWait: # optional
