name: PromptEndpoints
jobs:
  getprompt:
    name: Get JSON Property
    uses: notiz-dev/json-property@v0.2.0
    with: 
        path: 'fewshotprompts/respondtoappquestions.json'
        prop_path: 'messages'
  sendtoHF:
    name: HTTP Request Action
    uses: fjogeleit/http-request-action@v1.14.1
    with:
      # Request URL
      url: https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-beta
      # Request Method
      method: POST
      # Content Type
      contentType: application/json
      # Request Body as JSON String
      data: ${{ prop_path }}
      timeout: 5000
      # Bearer Authentication Token
      bearerToken: ${{ secrets.HF_API }}
      # Prevent this Action to fail if the request respond without an response
      preventFailureOnNoResponse: # optional
      # Prevent this Action to fail if the request respond with one of the configured StatusCodes
      ignoreStatusCodes: # optional
      # Certificate authority as string in PEM format
      httpsCA: # optional
      # Persist the response data to the specified file path
      responseFile: log/responses.txt
      # optional amount of retries if the request fails
      retry: # optional
      # wait time between retries in milliseconds
      retryWait: # optional
